version: '3.8'

services:
  target1:
    platform: linux/amd64
    image: vulnerables/web-dvwa
    networks:
      pentest_network:
        ipv4_address: 172.18.0.2
    ports:
      - "80:80"
    container_name: target1

  target2:
    platform: linux/amd64
    image: nginx:stable
    networks:
      pentest_network:
        ipv4_address: 172.18.0.4
    ports:
      - "8080:80"
    container_name: target2

  llm-pentest:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
      - .:/app
    networks:
      pentest_network:
        ipv4_address: 172.18.0.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - TARGET1_IP=172.18.0.2
      - TARGET2_IP=172.18.0.4
    tty: true
    stdin_open: true
    container_name: llm-pentest

networks:
  pentest_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16